---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "k8sj-io-new"
spec:
  secretName: "k8sj-io-tls-new"
  issuerRef:
    name: le-prod
    kind: ClusterIssuer
  commonName: "k8sj.io"
  dnsNames:
    - "k8sj.io"
    - "*.k8sj.io"
