---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: envoy-gateway
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: envoy-gateway
      namespace: networking
  interval: 1h
  path: "./k8s/apps/networking/envoy-gateway/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: networking
  timeout: 5m

---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-config
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: envoy-gateway
  dependsOn:
    - name: envoy-gateway
  interval: 1h
  path: "./k8s/apps/networking/envoy-gateway/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: networking
  timeout: 5m
