---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname ledfx
  namespace: flux-system
spec:
  targetNamespace: ledfx
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./k8s/apps/home-automation/ledfx/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  dependsOn:
    - name: cluster-apps-multus
    - name: cluster-apps-rook-ceph-cluster
  postBuild:
    substitute:
      APP: *appname
      APP_UID: "1000"
      APP_GID: "1000"
      VOLSYNC_CLAIM: ledfx
