---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: unifi-controller
  namespace: networking
spec:
  targetRefs:
    group: ""
    kind: Service
    name: unifi-controller
  tls:
    mode: Simple
