---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: unifi-controller
  namespace: networking
spec:
  endpoints:
    - fqdn:
        hostname: unifi-controller.networking.svc.cluster.local
        port: 8443
  tls:
    insecureSkipVerify: true
