---
apiVersion: v1
kind: Service
metadata:
  name: &name hyperhdr
  namespace: networking
  labels:
    app.kubernetes.io/name: &name
    app.kubernetes.io/instance: &name
spec:
  type: ExternalName
  externalName: 192.168.0.5
  ports:
    - name: http
      port: &port 8090
      protocol: TCP
      targetPort: *port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &name
  namespace: networking
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/appName: "HyperHFR"
    hajimari.io/icon: mdi:hdr
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
  labels:
    app.kubernetes.io/name: &name
    app.kubernetes.io/instance: &name
spec:
  ingressClassName: nginx
  rules:
    - host: &host hyperhdr.k8sj.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: &name
                port:
                  number: 80
  tls:
    - hosts:
        - *host
