---
apiVersion: v1
kind: Service
metadata:
  name: hyperhdr-headless
  namespace: networking
spec:
  clusterIP: None
  ports:
    - port: 8090
      protocol: TCP
      name: http

---
apiVersion: v1
kind: Endpoints
metadata:
  name: hyperhdr-headless
  namespace: networking
subsets:
  - addresses:
      - hostname: hyperhdr.dom.lan
    ports:
      - port: 8090
        name: http

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hyperhdr
  namespace: networking
spec:
  parentRefs:
    - name: envoy-internal
      namespace: networking
  hostnames:
    - hyperhdr.k8sj.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hyperhdr-headless
          kind: Service
          port: 8090
          weight: 1
